services:
  - type: web
    name: laravel-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    ports:
      - port: 8080
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        fromSecret: APP_KEY_SECRET
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: laravel-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: laravel-db
          property: password

databases:
  - name: laravel-db
    region: oregon
    engine: postgresql
    version: "15"
    plan: starter
